spring.application.name=pethost
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/pethost
spring.datasource.username=postgres
spring.datasource.password=1234

server.error.whitelabel.enabled=false



security.jwt.secret-key=cade939328f8b7041ea384ce456fcadc326dc546a51096a3685ce795c664c39e
security.jwt.expiration-time=3600000
spring.jpa.hibernate.ddl-auto=update


cloudflare.r2.access-key-id=e2513d2df84f6326d07319b84464bb7b
cloudflare.r2.secret-access-key=sQasHAvsbeyTNOSEDDTck5Qy4UU8exlX3Lc2Eq1T
cloudflare.r2.endpoint=https://e2513d2df84f6326d07319b84464bb7b.r2.cloudflarestorage.com
cloudflare.api.token=c0cd7c4531bee889d33ca85a7d134a16dfef0
cloudflare.api.global-key=c0cd7c4531bee889d33ca85a7d134a16dfef0
cloudflare.api.origin-key=v1.0-d628ea4ea21ca3d31b68e6b0-734a18cd5cc23f41c381e2ff90a8e38c68fce6840bb5fe7e2288d6f35013ad9f49be21dda0514871985bf6de0a616be2f453b7ced9ccd0e94a3c696a2959b4cad38a393a9ec3172545








logging.level.root=DEBUG
